# Generated by Django 4.0.5 on 2022-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_rename_username_vote_user_remove_vote_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='action_type',
            field=models.CharField(choices=[('1', 1), ('0', 0), ('-1', -1)], default=0, max_length=20),
        ),
    ]
