# Generated by Django 4.0.5 on 2022-06-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='question',
            name='username',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='username',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
