# Generated by Django 4.0.5 on 2022-06-10 15:26

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_user_rating_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.models.uploading),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[['0', 'Newbie'], ['1', 'Apprentice'], ['2', 'Thinker'], ['3', 'Master'], ['4', 'Genius'], ['5', 'Higher Intelligence']], default='0', max_length=20, verbose_name='user title'),
        ),
    ]
