# Generated by Django 4.0.5 on 2022-06-14 14:25

from django.db import migrations, models
import user_profile.services


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_remove_user_avatar_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=user_profile.services.uploading),
        ),
    ]
