# Generated by Django 4.0.5 on 2022-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
