# Generated by Django 4.0.5 on 2022-06-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_answer_options_remove_answer_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answers', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questions', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='votes',
            options={'verbose_name': 'Votes', 'verbose_name_plural': 'Votes'},
        ),
    ]
