# Generated by Django 4.0.5 on 2022-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
