# Generated by Django 4.0.5 on 2022-06-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_votes_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='question',
        ),
    ]
