# Generated by Django 4.0.5 on 2022-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_remove_comment_answer_remove_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='social.tag', verbose_name='User`s tag(s)'),
        ),
    ]
