# Generated by Django 4.0.5 on 2022-06-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_answer_content_alter_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='votes',
            old_name='username',
            new_name='user',
        ),
    ]
