# Generated by Django 4.0.5 on 2022-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_vote_alter_answer_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
