# Generated by Django 4.0.5 on 2022-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_remove_tag_slug_alter_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
